files:
    copy:
        - .env

post_create:
    - pnpm install

pre_merge:
    - pnpm lint
    - pnpm build

panes:
    - command: <agent>
      focus: true
    - split: horizontal
      percentage: 50
