#!/usr/bin/env bash
# Make nginx see the visitor's IP instead of the Cloudflare edge IP.
# Writes /etc/nginx/conf.d/cloudflare-real-ip.conf from Cloudflare's published
# ranges, validates, reloads. Safe to re-run when the ranges change.
# Usage (from a laptop): just real-ip-apply
set -euo pipefail

conf=/etc/nginx/conf.d/cloudflare-real-ip.conf
tmp="$(mktemp)"
backup=""
trap 'rm -f "$tmp" "$backup"' EXIT

v4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS https://www.cloudflare.com/ips-v6)"
for range in $v4 $v6; do
	if ! [[ "$range" =~ ^[0-9a-f.:]+/[0-9]+$ ]]; then
		echo "unexpected Cloudflare IP list entry '$range', aborting" >&2
		exit 1
	fi
done
if [ -z "$v4" ] || [ -z "$v6" ]; then
	echo "empty Cloudflare IP list, aborting" >&2
	exit 1
fi

{
	echo "# Generated by infra/nginx/cloudflare-real-ip.sh — do not edit by hand."
	for range in $v4 $v6; do
		echo "set_real_ip_from $range;"
	done
	# Only trusted when the TCP peer is a Cloudflare edge, so a client that
	# reaches the VPS directly cannot spoof it. Local callers (the cron
	# wrappers on 127.0.0.1) keep their own address.
	echo "real_ip_header CF-Connecting-IP;"
} >"$tmp"

if [ -f "$conf" ]; then
	backup="$(mktemp)"
	cp "$conf" "$backup"
fi

install -m 644 "$tmp" "$conf"
if ! nginx -t; then
	if [ -n "$backup" ]; then
		cp "$backup" "$conf"
	else
		rm -f "$conf"
	fi
	echo "nginx -t failed, previous config restored" >&2
	exit 1
fi
systemctl reload nginx
echo "wrote $conf ($(grep -c set_real_ip_from "$conf") ranges), nginx reloaded"
