/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaihdaSalasanaRouteImport } from './routes/vaihda-salasana'
import { Route as VahvistaSahkopostiRouteImport } from './routes/vahvista-sahkoposti'
import { Route as UnohdinSalasananRouteImport } from './routes/unohdin-salasanan'
import { Route as TietosuojaRouteImport } from './routes/tietosuoja'
import { Route as TaydennaProfiiliRouteImport } from './routes/taydenna-profiili'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RekisteroidyRouteImport } from './routes/rekisteroidy'
import { Route as KirjauduRouteImport } from './routes/kirjaudu'
import { Route as KayttoehdotRouteImport } from './routes/kayttoehdot'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OmatIndexRouteImport } from './routes/omat/index'
import { Route as IlmoituksetIndexRouteImport } from './routes/ilmoitukset/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfiiliAsetuksetRouteImport } from './routes/profiili/asetukset'
import { Route as ProfiiliUserIdRouteImport } from './routes/profiili/$userId'
import { Route as IlmoituksetUusiRouteImport } from './routes/ilmoitukset/uusi'
import { Route as IlmoituksetListingIdRouteImport } from './routes/ilmoitukset/$listingId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as IlmoituksetListingIdMuokkaaRouteImport } from './routes/ilmoitukset/$listingId_.muokkaa'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VaihdaSalasanaRoute = VaihdaSalasanaRouteImport.update({
  id: '/vaihda-salasana',
  path: '/vaihda-salasana',
  getParentRoute: () => rootRouteImport,
} as any)
const VahvistaSahkopostiRoute = VahvistaSahkopostiRouteImport.update({
  id: '/vahvista-sahkoposti',
  path: '/vahvista-sahkoposti',
  getParentRoute: () => rootRouteImport,
} as any)
const UnohdinSalasananRoute = UnohdinSalasananRouteImport.update({
  id: '/unohdin-salasanan',
  path: '/unohdin-salasanan',
  getParentRoute: () => rootRouteImport,
} as any)
const TietosuojaRoute = TietosuojaRouteImport.update({
  id: '/tietosuoja',
  path: '/tietosuoja',
  getParentRoute: () => rootRouteImport,
} as any)
const TaydennaProfiiliRoute = TaydennaProfiiliRouteImport.update({
  id: '/taydenna-profiili',
  path: '/taydenna-profiili',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RekisteroidyRoute = RekisteroidyRouteImport.update({
  id: '/rekisteroidy',
  path: '/rekisteroidy',
  getParentRoute: () => rootRouteImport,
} as any)
const KirjauduRoute = KirjauduRouteImport.update({
  id: '/kirjaudu',
  path: '/kirjaudu',
  getParentRoute: () => rootRouteImport,
} as any)
const KayttoehdotRoute = KayttoehdotRouteImport.update({
  id: '/kayttoehdot',
  path: '/kayttoehdot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmatIndexRoute = OmatIndexRouteImport.update({
  id: '/omat/',
  path: '/omat/',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetIndexRoute = IlmoituksetIndexRouteImport.update({
  id: '/ilmoitukset/',
  path: '/ilmoitukset/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfiiliAsetuksetRoute = ProfiiliAsetuksetRouteImport.update({
  id: '/profiili/asetukset',
  path: '/profiili/asetukset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiiliUserIdRoute = ProfiiliUserIdRouteImport.update({
  id: '/profiili/$userId',
  path: '/profiili/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetUusiRoute = IlmoituksetUusiRouteImport.update({
  id: '/ilmoitukset/uusi',
  path: '/ilmoitukset/uusi',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetListingIdRoute = IlmoituksetListingIdRouteImport.update({
  id: '/ilmoitukset/$listingId',
  path: '/ilmoitukset/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const IlmoituksetListingIdMuokkaaRoute =
  IlmoituksetListingIdMuokkaaRouteImport.update({
    id: '/ilmoitukset/$listingId_/muokkaa',
    path: '/ilmoitukset/$listingId/muokkaa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kirjaudu': typeof KirjauduRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taydenna-profiili': typeof TaydennaProfiiliRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/unohdin-salasanan': typeof UnohdinSalasananRoute
  '/vahvista-sahkoposti': typeof VahvistaSahkopostiRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ilmoitukset/$listingId': typeof IlmoituksetListingIdRoute
  '/ilmoitukset/uusi': typeof IlmoituksetUusiRoute
  '/profiili/$userId': typeof ProfiiliUserIdRoute
  '/profiili/asetukset': typeof ProfiiliAsetuksetRoute
  '/admin/': typeof AdminIndexRoute
  '/ilmoitukset/': typeof IlmoituksetIndexRoute
  '/omat/': typeof OmatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ilmoitukset/$listingId/muokkaa': typeof IlmoituksetListingIdMuokkaaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kirjaudu': typeof KirjauduRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taydenna-profiili': typeof TaydennaProfiiliRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/unohdin-salasanan': typeof UnohdinSalasananRoute
  '/vahvista-sahkoposti': typeof VahvistaSahkopostiRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ilmoitukset/$listingId': typeof IlmoituksetListingIdRoute
  '/ilmoitukset/uusi': typeof IlmoituksetUusiRoute
  '/profiili/$userId': typeof ProfiiliUserIdRoute
  '/profiili/asetukset': typeof ProfiiliAsetuksetRoute
  '/admin': typeof AdminIndexRoute
  '/ilmoitukset': typeof IlmoituksetIndexRoute
  '/omat': typeof OmatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ilmoitukset/$listingId/muokkaa': typeof IlmoituksetListingIdMuokkaaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kirjaudu': typeof KirjauduRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taydenna-profiili': typeof TaydennaProfiiliRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/unohdin-salasanan': typeof UnohdinSalasananRoute
  '/vahvista-sahkoposti': typeof VahvistaSahkopostiRoute
  '/vaihda-salasana': typeof VaihdaSalasanaRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ilmoitukset/$listingId': typeof IlmoituksetListingIdRoute
  '/ilmoitukset/uusi': typeof IlmoituksetUusiRoute
  '/profiili/$userId': typeof ProfiiliUserIdRoute
  '/profiili/asetukset': typeof ProfiiliAsetuksetRoute
  '/admin/': typeof AdminIndexRoute
  '/ilmoitukset/': typeof IlmoituksetIndexRoute
  '/omat/': typeof OmatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ilmoitukset/$listingId_/muokkaa': typeof IlmoituksetListingIdMuokkaaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kayttoehdot'
    | '/kirjaudu'
    | '/rekisteroidy'
    | '/sitemap.xml'
    | '/taydenna-profiili'
    | '/tietosuoja'
    | '/unohdin-salasanan'
    | '/vahvista-sahkoposti'
    | '/vaihda-salasana'
    | '/admin/listings'
    | '/admin/users'
    | '/ilmoitukset/$listingId'
    | '/ilmoitukset/uusi'
    | '/profiili/$userId'
    | '/profiili/asetukset'
    | '/admin/'
    | '/ilmoitukset/'
    | '/omat/'
    | '/api/auth/$'
    | '/ilmoitukset/$listingId/muokkaa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kayttoehdot'
    | '/kirjaudu'
    | '/rekisteroidy'
    | '/sitemap.xml'
    | '/taydenna-profiili'
    | '/tietosuoja'
    | '/unohdin-salasanan'
    | '/vahvista-sahkoposti'
    | '/vaihda-salasana'
    | '/admin/listings'
    | '/admin/users'
    | '/ilmoitukset/$listingId'
    | '/ilmoitukset/uusi'
    | '/profiili/$userId'
    | '/profiili/asetukset'
    | '/admin'
    | '/ilmoitukset'
    | '/omat'
    | '/api/auth/$'
    | '/ilmoitukset/$listingId/muokkaa'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kayttoehdot'
    | '/kirjaudu'
    | '/rekisteroidy'
    | '/sitemap.xml'
    | '/taydenna-profiili'
    | '/tietosuoja'
    | '/unohdin-salasanan'
    | '/vahvista-sahkoposti'
    | '/vaihda-salasana'
    | '/admin/listings'
    | '/admin/users'
    | '/ilmoitukset/$listingId'
    | '/ilmoitukset/uusi'
    | '/profiili/$userId'
    | '/profiili/asetukset'
    | '/admin/'
    | '/ilmoitukset/'
    | '/omat/'
    | '/api/auth/$'
    | '/ilmoitukset/$listingId_/muokkaa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KayttoehdotRoute: typeof KayttoehdotRoute
  KirjauduRoute: typeof KirjauduRoute
  RekisteroidyRoute: typeof RekisteroidyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaydennaProfiiliRoute: typeof TaydennaProfiiliRoute
  TietosuojaRoute: typeof TietosuojaRoute
  UnohdinSalasananRoute: typeof UnohdinSalasananRoute
  VahvistaSahkopostiRoute: typeof VahvistaSahkopostiRoute
  VaihdaSalasanaRoute: typeof VaihdaSalasanaRoute
  IlmoituksetListingIdRoute: typeof IlmoituksetListingIdRoute
  IlmoituksetUusiRoute: typeof IlmoituksetUusiRoute
  ProfiiliUserIdRoute: typeof ProfiiliUserIdRoute
  ProfiiliAsetuksetRoute: typeof ProfiiliAsetuksetRoute
  IlmoituksetIndexRoute: typeof IlmoituksetIndexRoute
  OmatIndexRoute: typeof OmatIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  IlmoituksetListingIdMuokkaaRoute: typeof IlmoituksetListingIdMuokkaaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaihda-salasana': {
      id: '/vaihda-salasana'
      path: '/vaihda-salasana'
      fullPath: '/vaihda-salasana'
      preLoaderRoute: typeof VaihdaSalasanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vahvista-sahkoposti': {
      id: '/vahvista-sahkoposti'
      path: '/vahvista-sahkoposti'
      fullPath: '/vahvista-sahkoposti'
      preLoaderRoute: typeof VahvistaSahkopostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unohdin-salasanan': {
      id: '/unohdin-salasanan'
      path: '/unohdin-salasanan'
      fullPath: '/unohdin-salasanan'
      preLoaderRoute: typeof UnohdinSalasananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tietosuoja': {
      id: '/tietosuoja'
      path: '/tietosuoja'
      fullPath: '/tietosuoja'
      preLoaderRoute: typeof TietosuojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taydenna-profiili': {
      id: '/taydenna-profiili'
      path: '/taydenna-profiili'
      fullPath: '/taydenna-profiili'
      preLoaderRoute: typeof TaydennaProfiiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekisteroidy': {
      id: '/rekisteroidy'
      path: '/rekisteroidy'
      fullPath: '/rekisteroidy'
      preLoaderRoute: typeof RekisteroidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirjaudu': {
      id: '/kirjaudu'
      path: '/kirjaudu'
      fullPath: '/kirjaudu'
      preLoaderRoute: typeof KirjauduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayttoehdot': {
      id: '/kayttoehdot'
      path: '/kayttoehdot'
      fullPath: '/kayttoehdot'
      preLoaderRoute: typeof KayttoehdotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omat/': {
      id: '/omat/'
      path: '/omat'
      fullPath: '/omat/'
      preLoaderRoute: typeof OmatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/': {
      id: '/ilmoitukset/'
      path: '/ilmoitukset'
      fullPath: '/ilmoitukset/'
      preLoaderRoute: typeof IlmoituksetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/profiili/asetukset': {
      id: '/profiili/asetukset'
      path: '/profiili/asetukset'
      fullPath: '/profiili/asetukset'
      preLoaderRoute: typeof ProfiiliAsetuksetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiili/$userId': {
      id: '/profiili/$userId'
      path: '/profiili/$userId'
      fullPath: '/profiili/$userId'
      preLoaderRoute: typeof ProfiiliUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/uusi': {
      id: '/ilmoitukset/uusi'
      path: '/ilmoitukset/uusi'
      fullPath: '/ilmoitukset/uusi'
      preLoaderRoute: typeof IlmoituksetUusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/$listingId': {
      id: '/ilmoitukset/$listingId'
      path: '/ilmoitukset/$listingId'
      fullPath: '/ilmoitukset/$listingId'
      preLoaderRoute: typeof IlmoituksetListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/ilmoitukset/$listingId_/muokkaa': {
      id: '/ilmoitukset/$listingId_/muokkaa'
      path: '/ilmoitukset/$listingId/muokkaa'
      fullPath: '/ilmoitukset/$listingId/muokkaa'
      preLoaderRoute: typeof IlmoituksetListingIdMuokkaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminListingsRoute: typeof AdminListingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminListingsRoute: AdminListingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KayttoehdotRoute: KayttoehdotRoute,
  KirjauduRoute: KirjauduRoute,
  RekisteroidyRoute: RekisteroidyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaydennaProfiiliRoute: TaydennaProfiiliRoute,
  TietosuojaRoute: TietosuojaRoute,
  UnohdinSalasananRoute: UnohdinSalasananRoute,
  VahvistaSahkopostiRoute: VahvistaSahkopostiRoute,
  VaihdaSalasanaRoute: VaihdaSalasanaRoute,
  IlmoituksetListingIdRoute: IlmoituksetListingIdRoute,
  IlmoituksetUusiRoute: IlmoituksetUusiRoute,
  ProfiiliUserIdRoute: ProfiiliUserIdRoute,
  ProfiiliAsetuksetRoute: ProfiiliAsetuksetRoute,
  IlmoituksetIndexRoute: IlmoituksetIndexRoute,
  OmatIndexRoute: OmatIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  IlmoituksetListingIdMuokkaaRoute: IlmoituksetListingIdMuokkaaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
