/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IlmoituksetIndexRouteImport } from './routes/ilmoitukset/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as IlmoituksetUusiRouteImport } from './routes/ilmoitukset/uusi'
import { Route as IlmoituksetListingIdRouteImport } from './routes/ilmoitukset/$listingId'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as IlmoituksetListingIdMuokkaaRouteImport } from './routes/ilmoitukset/$listingId_.muokkaa'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetIndexRoute = IlmoituksetIndexRouteImport.update({
  id: '/ilmoitukset/',
  path: '/ilmoitukset/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetUusiRoute = IlmoituksetUusiRouteImport.update({
  id: '/ilmoitukset/uusi',
  path: '/ilmoitukset/uusi',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetListingIdRoute = IlmoituksetListingIdRouteImport.update({
  id: '/ilmoitukset/$listingId',
  path: '/ilmoitukset/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmoituksetListingIdMuokkaaRoute =
  IlmoituksetListingIdMuokkaaRouteImport.update({
    id: '/ilmoitukset/$listingId_/muokkaa',
    path: '/ilmoitukset/$listingId/muokkaa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/ilmoitukset/$listingId': typeof IlmoituksetListingIdRoute
  '/ilmoitukset/uusi': typeof IlmoituksetUusiRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ilmoitukset/': typeof IlmoituksetIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ilmoitukset/$listingId/muokkaa': typeof IlmoituksetListingIdMuokkaaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/ilmoitukset/$listingId': typeof IlmoituksetListingIdRoute
  '/ilmoitukset/uusi': typeof IlmoituksetUusiRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/ilmoitukset': typeof IlmoituksetIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ilmoitukset/$listingId/muokkaa': typeof IlmoituksetListingIdMuokkaaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/ilmoitukset/$listingId': typeof IlmoituksetListingIdRoute
  '/ilmoitukset/uusi': typeof IlmoituksetUusiRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ilmoitukset/': typeof IlmoituksetIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ilmoitukset/$listingId_/muokkaa': typeof IlmoituksetListingIdMuokkaaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/ilmoitukset/$listingId'
    | '/ilmoitukset/uusi'
    | '/profile/$userId'
    | '/profile/settings'
    | '/dashboard/'
    | '/ilmoitukset/'
    | '/api/auth/$'
    | '/ilmoitukset/$listingId/muokkaa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/ilmoitukset/$listingId'
    | '/ilmoitukset/uusi'
    | '/profile/$userId'
    | '/profile/settings'
    | '/dashboard'
    | '/ilmoitukset'
    | '/api/auth/$'
    | '/ilmoitukset/$listingId/muokkaa'
  id:
    | '__root__'
    | '/'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/ilmoitukset/$listingId'
    | '/ilmoitukset/uusi'
    | '/profile/$userId'
    | '/profile/settings'
    | '/dashboard/'
    | '/ilmoitukset/'
    | '/api/auth/$'
    | '/ilmoitukset/$listingId_/muokkaa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  IlmoituksetListingIdRoute: typeof IlmoituksetListingIdRoute
  IlmoituksetUusiRoute: typeof IlmoituksetUusiRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  IlmoituksetIndexRoute: typeof IlmoituksetIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  IlmoituksetListingIdMuokkaaRoute: typeof IlmoituksetListingIdMuokkaaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/': {
      id: '/ilmoitukset/'
      path: '/ilmoitukset'
      fullPath: '/ilmoitukset/'
      preLoaderRoute: typeof IlmoituksetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/uusi': {
      id: '/ilmoitukset/uusi'
      path: '/ilmoitukset/uusi'
      fullPath: '/ilmoitukset/uusi'
      preLoaderRoute: typeof IlmoituksetUusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/$listingId': {
      id: '/ilmoitukset/$listingId'
      path: '/ilmoitukset/$listingId'
      fullPath: '/ilmoitukset/$listingId'
      preLoaderRoute: typeof IlmoituksetListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmoitukset/$listingId_/muokkaa': {
      id: '/ilmoitukset/$listingId_/muokkaa'
      path: '/ilmoitukset/$listingId/muokkaa'
      fullPath: '/ilmoitukset/$listingId/muokkaa'
      preLoaderRoute: typeof IlmoituksetListingIdMuokkaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  IlmoituksetListingIdRoute: IlmoituksetListingIdRoute,
  IlmoituksetUusiRoute: IlmoituksetUusiRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  IlmoituksetIndexRoute: IlmoituksetIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  IlmoituksetListingIdMuokkaaRoute: IlmoituksetListingIdMuokkaaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
