/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PyoratUusiRouteImport } from './routes/pyorat/uusi'
import { Route as PyoratVehicleIdRouteImport } from './routes/pyorat/$vehicleId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as ApiImagesUploadRouteImport } from './routes/api/images/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PyoratUusiRoute = PyoratUusiRouteImport.update({
  id: '/pyorat/uusi',
  path: '/pyorat/uusi',
  getParentRoute: () => rootRouteImport,
} as any)
const PyoratVehicleIdRoute = PyoratVehicleIdRouteImport.update({
  id: '/pyorat/$vehicleId',
  path: '/pyorat/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesUploadRoute = ApiImagesUploadRouteImport.update({
  id: '/api/images/upload',
  path: '/api/images/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/pyorat/$vehicleId': typeof PyoratVehicleIdRoute
  '/pyorat/uusi': typeof PyoratUusiRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/pyorat/$vehicleId': typeof PyoratVehicleIdRoute
  '/pyorat/uusi': typeof PyoratUusiRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/pyorat/$vehicleId': typeof PyoratVehicleIdRoute
  '/pyorat/uusi': typeof PyoratUusiRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/pyorat/$vehicleId'
    | '/pyorat/uusi'
    | '/api/images/upload'
    | '/api/uploads/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/pyorat/$vehicleId'
    | '/pyorat/uusi'
    | '/api/images/upload'
    | '/api/uploads/$'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/pyorat/$vehicleId'
    | '/pyorat/uusi'
    | '/api/images/upload'
    | '/api/uploads/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PyoratVehicleIdRoute: typeof PyoratVehicleIdRoute
  PyoratUusiRoute: typeof PyoratUusiRoute
  ApiImagesUploadRoute: typeof ApiImagesUploadRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyorat/uusi': {
      id: '/pyorat/uusi'
      path: '/pyorat/uusi'
      fullPath: '/pyorat/uusi'
      preLoaderRoute: typeof PyoratUusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyorat/$vehicleId': {
      id: '/pyorat/$vehicleId'
      path: '/pyorat/$vehicleId'
      fullPath: '/pyorat/$vehicleId'
      preLoaderRoute: typeof PyoratVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/upload': {
      id: '/api/images/upload'
      path: '/api/images/upload'
      fullPath: '/api/images/upload'
      preLoaderRoute: typeof ApiImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  PyoratVehicleIdRoute: PyoratVehicleIdRoute,
  PyoratUusiRoute: PyoratUusiRoute,
  ApiImagesUploadRoute: ApiImagesUploadRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
