/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AsetuksetRouteImport } from './routes/asetukset'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PyoratUusiRouteImport } from './routes/pyorat/uusi'
import { Route as PyoratVehicleIdRouteImport } from './routes/pyorat/$vehicleId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as PyoratVehicleIdMuistutuksetRouteImport } from './routes/pyorat/$vehicleId_.muistutukset'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as ApiImagesUploadRouteImport } from './routes/api/images/upload'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'
import { Route as PyoratVehicleIdHuoltoUusiRouteImport } from './routes/pyorat/$vehicleId_.huolto.uusi'

const AsetuksetRoute = AsetuksetRouteImport.update({
  id: '/asetukset',
  path: '/asetukset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PyoratUusiRoute = PyoratUusiRouteImport.update({
  id: '/pyorat/uusi',
  path: '/pyorat/uusi',
  getParentRoute: () => rootRouteImport,
} as any)
const PyoratVehicleIdRoute = PyoratVehicleIdRouteImport.update({
  id: '/pyorat/$vehicleId',
  path: '/pyorat/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const PyoratVehicleIdMuistutuksetRoute =
  PyoratVehicleIdMuistutuksetRouteImport.update({
    id: '/pyorat/$vehicleId_/muistutukset',
    path: '/pyorat/$vehicleId/muistutukset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesUploadRoute = ApiImagesUploadRouteImport.update({
  id: '/api/images/upload',
  path: '/api/images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PyoratVehicleIdHuoltoUusiRoute =
  PyoratVehicleIdHuoltoUusiRouteImport.update({
    id: '/pyorat/$vehicleId_/huolto/uusi',
    path: '/pyorat/$vehicleId/huolto/uusi',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asetukset': typeof AsetuksetRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/pyorat/$vehicleId': typeof PyoratVehicleIdRoute
  '/pyorat/uusi': typeof PyoratUusiRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/pyorat/$vehicleId/muistutukset': typeof PyoratVehicleIdMuistutuksetRoute
  '/pyorat/$vehicleId/huolto/uusi': typeof PyoratVehicleIdHuoltoUusiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asetukset': typeof AsetuksetRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/pyorat/$vehicleId': typeof PyoratVehicleIdRoute
  '/pyorat/uusi': typeof PyoratUusiRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/pyorat/$vehicleId/muistutukset': typeof PyoratVehicleIdMuistutuksetRoute
  '/pyorat/$vehicleId/huolto/uusi': typeof PyoratVehicleIdHuoltoUusiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asetukset': typeof AsetuksetRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/pyorat/$vehicleId': typeof PyoratVehicleIdRoute
  '/pyorat/uusi': typeof PyoratUusiRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/pyorat/$vehicleId_/muistutukset': typeof PyoratVehicleIdMuistutuksetRoute
  '/pyorat/$vehicleId_/huolto/uusi': typeof PyoratVehicleIdHuoltoUusiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asetukset'
    | '/api/cron'
    | '/api/health'
    | '/pyorat/$vehicleId'
    | '/pyorat/uusi'
    | '/api/documents/upload'
    | '/api/images/upload'
    | '/api/uploads/$'
    | '/pyorat/$vehicleId/muistutukset'
    | '/pyorat/$vehicleId/huolto/uusi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asetukset'
    | '/api/cron'
    | '/api/health'
    | '/pyorat/$vehicleId'
    | '/pyorat/uusi'
    | '/api/documents/upload'
    | '/api/images/upload'
    | '/api/uploads/$'
    | '/pyorat/$vehicleId/muistutukset'
    | '/pyorat/$vehicleId/huolto/uusi'
  id:
    | '__root__'
    | '/'
    | '/asetukset'
    | '/api/cron'
    | '/api/health'
    | '/pyorat/$vehicleId'
    | '/pyorat/uusi'
    | '/api/documents/upload'
    | '/api/images/upload'
    | '/api/uploads/$'
    | '/pyorat/$vehicleId_/muistutukset'
    | '/pyorat/$vehicleId_/huolto/uusi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsetuksetRoute: typeof AsetuksetRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PyoratVehicleIdRoute: typeof PyoratVehicleIdRoute
  PyoratUusiRoute: typeof PyoratUusiRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
  ApiImagesUploadRoute: typeof ApiImagesUploadRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
  PyoratVehicleIdMuistutuksetRoute: typeof PyoratVehicleIdMuistutuksetRoute
  PyoratVehicleIdHuoltoUusiRoute: typeof PyoratVehicleIdHuoltoUusiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/asetukset': {
      id: '/asetukset'
      path: '/asetukset'
      fullPath: '/asetukset'
      preLoaderRoute: typeof AsetuksetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyorat/uusi': {
      id: '/pyorat/uusi'
      path: '/pyorat/uusi'
      fullPath: '/pyorat/uusi'
      preLoaderRoute: typeof PyoratUusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyorat/$vehicleId': {
      id: '/pyorat/$vehicleId'
      path: '/pyorat/$vehicleId'
      fullPath: '/pyorat/$vehicleId'
      preLoaderRoute: typeof PyoratVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyorat/$vehicleId_/muistutukset': {
      id: '/pyorat/$vehicleId_/muistutukset'
      path: '/pyorat/$vehicleId/muistutukset'
      fullPath: '/pyorat/$vehicleId/muistutukset'
      preLoaderRoute: typeof PyoratVehicleIdMuistutuksetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/upload': {
      id: '/api/images/upload'
      path: '/api/images/upload'
      fullPath: '/api/images/upload'
      preLoaderRoute: typeof ApiImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyorat/$vehicleId_/huolto/uusi': {
      id: '/pyorat/$vehicleId_/huolto/uusi'
      path: '/pyorat/$vehicleId/huolto/uusi'
      fullPath: '/pyorat/$vehicleId/huolto/uusi'
      preLoaderRoute: typeof PyoratVehicleIdHuoltoUusiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsetuksetRoute: AsetuksetRoute,
  ApiCronRoute: ApiCronRoute,
  ApiHealthRoute: ApiHealthRoute,
  PyoratVehicleIdRoute: PyoratVehicleIdRoute,
  PyoratUusiRoute: PyoratUusiRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
  ApiImagesUploadRoute: ApiImagesUploadRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
  PyoratVehicleIdMuistutuksetRoute: PyoratVehicleIdMuistutuksetRoute,
  PyoratVehicleIdHuoltoUusiRoute: PyoratVehicleIdHuoltoUusiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
